CREATE TABLE IF NOT EXISTS Url (
  LONGURL VARCHAR(50) NOT NULL,
  SHORTURL VARCHAR(50) NOT NULL,
  CREATEDDATE VARCHAR(50) NOT NULL,
  MODIFIEDDate VARCHAR(50) NOT NULL,
  COUNT VARCHAR(50) NOT NULL
);
