CREATE TABLE IF NOT EXISTS url (
  LONGURL VARCHAR(50) NOT NULL,
  SHORTURL VARCHAR(50) NOT NULL,
  CREATEDDATE VARCHAR(50) NOT NULL,
  LAST_ACCESSED_AT VARCHAR(50) NOT NULL,
  COUNT VARCHAR(50) NOT NULL
);
